import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Clock, ArrowRight, ArrowLeft, Check } from 'lucide-react';
import LoadingSpinner from '../../components/ui/LoadingSpinner';
import api from '../../services/api';
import toast from 'react-hot-toast';

const BookAppointment = () => {
  const navigate = useNavigate(); const [step, setStep] = useState(1); const [departments, setDepartments] = useState([]); const [doctors, setDoctors] = useState([]); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
  const [selectedDept, setSelectedDept] = useState(null); const [selectedDoctor, setSelectedDoctor] = useState(null); const [date, setDate] = useState(''); const [timeSlot, setTimeSlot] = useState(''); const [symptoms, setSymptoms] = useState(''); const [type, setType] = useState('consultation');
  const timeSlots = ['09:00 AM','09:30 AM','10:00 AM','10:30 AM','11:00 AM','11:30 AM','12:00 PM','02:00 PM','02:30 PM','03:00 PM','03:30 PM','04:00 PM','04:30 PM'];
  useEffect(() => { (async () => { try { const r = await api.get('/departments'); setDepartments(r.data.data); } catch(e){} finally { setLoading(false); } })(); }, []);
  useEffect(() => { if(selectedDept) { (async () => { try { const r = await api.get('/doctors',{params:{department:selectedDept._id}}); setDoctors(r.data.data); } catch(e){} })(); } }, [selectedDept]);
  const handleSubmit = async () => { setSubmitting(true); try { await api.post('/appointments',{doctor:selectedDoctor._id,department:selectedDept._id,date,timeSlot,symptoms,type}); toast.success('Booked!'); navigate('/patient/appointments'); } catch(e) { toast.error(e.response?.data?.message||'Failed'); } finally { setSubmitting(false); } };
  const today = new Date().toISOString().split('T')[0];
  if (loading) return <LoadingSpinner />;
  return (
    <div className="animate-fade-in">
      <div style={{ marginBottom:32 }}><h1 style={{ fontSize:28, fontWeight:800, marginBottom:4 }}>Book Appointment</h1><p style={{ color:'var(--text-muted)', fontSize:14 }}>Follow the steps to schedule your visit</p></div>
      <div style={{ display:'flex', alignItems:'center', gap:0, marginBottom:40, maxWidth:600 }}>
        {['Department','Doctor','Schedule','Confirm'].map((label,i) => (
          <div key={i} style={{ display:'flex', alignItems:'center', flex:i<3?1:'none' }}>
            <div style={{ display:'flex', flexDirection:'column', alignItems:'center', gap:6 }}>
              <div style={{ width:36, height:36, borderRadius:'50%', display:'flex', alignItems:'center', justifyContent:'center', fontSize:14, fontWeight:700, background:step>i+1?'var(--accent)':step===i+1?'var(--primary)':'var(--bg-tertiary)', color:'white', transition:'all 0.3s' }}>{step>i+1?<Check size={18}/>:i+1}</div>
              <span style={{ fontSize:11, fontWeight:500, color:step>=i+1?'var(--text-primary)':'var(--text-muted)' }}>{label}</span>
            </div>
            {i<3 && <div style={{ flex:1, height:2, background:step>i+1?'var(--accent)':'var(--bg-tertiary)', margin:'0 12px', marginBottom:22 }}/>}
          </div>
        ))}
      </div>
      {step===1 && <div className="animate-fade-in"><h2 style={{ fontSize:20, fontWeight:700, marginBottom:20 }}>Select Department</h2><div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(200px, 1fr))', gap:16 }}>{departments.map(d => (<div key={d._id} onClick={()=>{setSelectedDept(d);setStep(2);}} className="glass-card" style={{ padding:24, textAlign:'center', cursor:'pointer' }}><div style={{ fontSize:40, marginBottom:12 }}>{d.icon}</div><h4 style={{ fontSize:15, fontWeight:600 }}>{d.name}</h4></div>))}</div></div>}
      {step===2 && <div className="animate-fade-in"><h2 style={{ fontSize:20, fontWeight:700, marginBottom:20 }}>Select Doctor — {selectedDept?.name}</h2>{doctors.length>0?<div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill, minmax(280px, 1fr))', gap:16 }}>{doctors.map(d => (<div key={d._id} onClick={()=>{setSelectedDoctor(d);setStep(3);}} className="glass-card" style={{ padding:24, cursor:'pointer' }}><div style={{ display:'flex', alignItems:'center', gap:16, marginBottom:16 }}><div style={{ width:48, height:48, borderRadius:'50%', background:'linear-gradient(135deg, var(--primary), var(--secondary))', display:'flex', alignItems:'center', justifyContent:'center', fontSize:18, fontWeight:700, color:'white' }}>{d.user?.name?.charAt(0)}</div><div><h4 style={{ fontSize:15, fontWeight:700 }}>{d.user?.name}</h4><p style={{ fontSize:13, color:'var(--primary-light)' }}>{d.specialization}</p></div></div><div style={{ display:'flex', justifyContent:'space-between', fontSize:13, color:'var(--text-secondary)' }}><span>{d.experience} yrs</span><span style={{ fontWeight:600, color:'var(--accent-light)' }}>₹{d.fees}</span></div></div>))}</div>:<div style={{ textAlign:'center', padding:60, color:'var(--text-muted)' }}>No doctors available</div>}<button className="btn btn-ghost" style={{ marginTop:24 }} onClick={()=>setStep(1)}><ArrowLeft size={16}/> Back</button></div>}
      {step===3 && <div className="animate-fade-in"><h2 style={{ fontSize:20, fontWeight:700, marginBottom:20 }}>Schedule</h2><div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:24, maxWidth:700 }}><div><div className="form-group" style={{ marginBottom:20 }}><label className="form-label">Date</label><input type="date" className="form-input" min={today} value={date} onChange={e=>setDate(e.target.value)}/></div><div className="form-group" style={{ marginBottom:20 }}><label className="form-label">Type</label><select className="form-select" value={type} onChange={e=>setType(e.target.value)}><option value="consultation">Consultation</option><option value="follow-up">Follow-up</option><option value="routine-checkup">Routine Checkup</option></select></div><div className="form-group"><label className="form-label">Symptoms</label><textarea className="form-textarea" value={symptoms} onChange={e=>setSymptoms(e.target.value)} placeholder="Describe symptoms..."/></div></div><div><label className="form-label">Time Slot</label><div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:8, marginTop:6 }}>{timeSlots.map(s => <button key={s} type="button" onClick={()=>setTimeSlot(s)} className={`btn btn-sm ${timeSlot===s?'btn-primary':'btn-ghost'}`} style={{ justifyContent:'center' }}><Clock size={14}/> {s}</button>)}</div></div></div><div style={{ display:'flex', gap:12, marginTop:28 }}><button className="btn btn-ghost" onClick={()=>setStep(2)}><ArrowLeft size={16}/> Back</button><button className="btn btn-primary" disabled={!date||!timeSlot} onClick={()=>setStep(4)}>Review <ArrowRight size={16}/></button></div></div>}
      {step===4 && <div className="animate-fade-in"><h2 style={{ fontSize:20, fontWeight:700, marginBottom:20 }}>Confirm Booking</h2><div className="glass-card" style={{ padding:32, maxWidth:500 }}><div style={{ display:'grid', gap:16 }}>{[{l:'Department',v:selectedDept?.name},{l:'Doctor',v:selectedDoctor?.user?.name},{l:'Date',v:date?new Date(date).toLocaleDateString('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric'}):''},{l:'Time',v:timeSlot},{l:'Fee',v:`₹${selectedDoctor?.fees}`}].map((item,i)=>(<div key={i} style={{ display:'flex', justifyContent:'space-between', padding:'8px 0', borderBottom:i<4?'1px solid var(--border)':'none' }}><span style={{ color:'var(--text-muted)', fontSize:14 }}>{item.l}</span><span style={{ fontWeight:600, fontSize:14 }}>{item.v}</span></div>))}</div></div><div style={{ display:'flex', gap:12, marginTop:28 }}><button className="btn btn-ghost" onClick={()=>setStep(3)}><ArrowLeft size={16}/> Back</button><button className="btn btn-accent btn-lg" onClick={handleSubmit} disabled={submitting}>{submitting?<div className="spinner" style={{width:20,height:20,borderWidth:2}}/>:<><Check size={18}/> Confirm Booking</>}</button></div></div>}
    </div>
  );
};
export default BookAppointment;
